trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  
jobs:
- job: Build
  displayName: Build
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
  - script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY/demoWebApp

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: buildArtifact

- deployment: VMDeploy
  displayName: IIS_Deploy
  pool:
    vmImage: 'windows-latest'
  environment: Test.ICPL13104
  dependsOn: Build
  strategy:
    runOnce:
      deploy:
        steps:
        - task: IISWebAppManagementOnMachineGroup@0
          inputs:
            iISDeploymentType: 'IISWebsite'
            actionIISWebsite: 'CreateOrUpdateWebsite'
            websiteName: 'testdeploy'
            websitePhysicalPath: 'D:\testdeploy' 
            websitePhysicalPathAuth: 'WebsiteUserPassThrough'
            addBinding: true 
            protocol: 'http' 
            iPAddress: 'All Unassigned'
            port: '82'
            bindings: 
            createOrUpdateAppPoolForWebsite: true
            appPoolNameForWebsite: 'testpool'
            dotNetVersionForWebsite: 'v4.0'
            appPoolIdentityForWebsite: 'ApplicationPoolIdentity'
        
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            webSiteName: 'testdeploy'
            package: 'C:\azagent\A3\_work\2\buildArtifact\WebApp.zip' 
