trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  displayName: Build
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: buildArtifact

- deployment: VMDeploy
  displayName: IIS_Deploy
  pool:
    vmImage: 'windows-latest'
  environment: Test.ICPL13104
  dependsOn: Build
  strategy:
    runOnce:
      deploy:
        steps:
        - task: IISWebAppManagementOnMachineGroup@0
          inputs:
            iISDeploymentType: 'IISWebsite'
            actionIISWebsite: 'CreateOrUpdateWebsite'
            websiteName: 'testdeploy'
            websitePhysicalPath: 'D:\testdeploy' 
            websitePhysicalPathAuth: 'WebsiteUserPassThrough'
            addBinding: true 
            protocol: 'http' 
            iPAddress: 'All Unassigned'
            port: '82'
            bindings: 
            createOrUpdateAppPoolForWebsite: true
            appPoolNameForWebsite: 'testpool'
            dotNetVersionForWebsite: 'v4.0'
            appPoolIdentityForWebsite: 'ApplicationPoolIdentity'
        
        - task: IISWebAppDeploymentOnMachineGroup@0
          inputs:
            webSiteName: 'testdeploy'
            package: 'C:\azagent\A3\_work\3\buildArtifact\WebApp.zip' 
